### PR TITLE
Fix miniGameBlock rubberbanding + some other improvements

### PR DESCRIPTION
**Pull request by Salads**
Happens when the parent of the block's transform is set.

Apparently caused by the PhotonTransformView's built-in Interpolation/Extrapolation network smoothing when we suddenly change the position of the block when setting it's transform parent.

This makes it so it simply passes and syncs the transform of the block, but currently does not apply any Interpolation/Extrapolation. In the future we could create a case where we only apply network smoothing techniques after the parent transform has been set, but this would require us to manually implement our own network smoothing techniques.

### CODE REVIEW

**Comment by scryptonite** [comment]
Hey Salads, thanks for submitting this PR!

Unfortunately, it appears that occasionally picking up and dropping a block with your changes will still show for a few frames the block flickering/jumping towards the console on the clients that do not own the block. It's a somewhat random occurrence, but it happens more frequently if you pickup and drop the block in succession a few times.

I don't think how Photon smooths the block between position updates is to blame for why the flicker is occurring in and of itself; it really only highlights to observers/game clients that the underlying method for calculating the difference is not well equipped to account for changes to the block's parent and/or is not synced properly with the RPC to change the parent&mdash;which I think would follow since the local position `0,0,0` in global space while under one parent is different from the same local position `0,0,0` while under another parent, and it appears to keep its local position relative to its last parent when its reparented, as evidenced by its habit of jumping to be near the console when dropped.

The only way I can think of fixing the block movement updates while also being able to change its parent (unlike when I decided to avoid having it change parents entirely, as merged in PR #11) is to sync the parent with the block's local position and then render the smoothed global position change ourselves. That way, when a position update arrives on the client, we just lerp between the block's old position under its old parent to the new position under its new parent, thereby avoiding the flicker of abrupt movement when the parent of the block needs to be changed because the client will have accounted for the parent's impact on the position of the block properly. 

If you want to try to tackle this, I can assign you to it so you kinda have first dibs of working on it; though it may not even necessary since I don't know whether Talima wants to revisit this bug or not for the sake of being able to change the block's parent.

<br>

My other thoughts about this pull is that it appears you're using a slightly outdated version of Unity (`5.5.2f1` vs `5.6.1f1`, as indicated in this PR's diff for /ProjectSettings/ProjectVersion.txt) and that you also committed Unity's automatic removal of /Assets/_theGAME/_NewAssets.meta, which is/was there to represent a directory that isn't supposed to be empty and should have been present (not something I expect that you to have been aware of).

/cc @teamTALIMA: adding a temporary [.gitkeep file like I've done](https://github.com/teamTALIMA/teamTALIMA_theGAME/pull/9/files#diff-e15a05cfb3af29e9fee3204bf0301d97) in PR #9 will make it so the directory appears in the repository, because git only tracks files. :)

<br><br><br>

@Salads Hopefully my response here won't discourage you from improving this pull or from contributing later with another one :P . Feel free to comment if you think it would be beneficial to work work towards improving the transform sync to support changing parents & if I can be of any help. 👍 

Thanks again

**Comment by Salads** [comment]
So I think the main problem was trying to update the block's position while the block has a transform parent. This gets around that by updating the block's transform only when it doesn't have a parent. That way, while the parent transform is still updating, we can sit back and let the parenting take care of updating the position. When the block doesn't have a parent, we update it normally with Linear Interpolation.

I kind of mashed in a bunch of other changes because at first it was gonna be a playground for me but then the forking for pull request is kind of dreadful. -.- If any of the changes are not wanted I can just make a new branch and update or something

@teamTALIMA 
I think Github lets people make free organization accounts, in which better security options can be set, like having the master branch can only be pushed to by admins and letting only certain people create branches in the repo. This way I was hoping we could do something like just create branches and then do merge requests into master.

##  List of Changes

1. Added `List<GameObject>` of Blocks in minigameBlockStack.cs to keep track of the blocks so we can delete them and do checks on them when things happen

2. minigameBlockStack now deletes the blocks after the game is won.

3. When instantiating minigameBlocks, changed regular `Instantiate` to `InstantiateSceneObject` to keep objects alive until the game is over or everyone leaves.

4. Introduced a readonly string `RoomName` used with `CreateOrJoinRoom` for maintenance purposes.

5. Got rid of the "win" variable, I feel this shouldn't be a variable but a if statement and then an RPC should be called to tell everyone the game was won.

6. Replaced the "M1" room properties gameactive with just a variable in the `minigameBlockStack` class that is synchronized over the network with an RPC call.

7. Updated Unity ;p

@scryptonite

**Comment by Salads** [comment]
So with this new commit, I think a big part of it was the ping/latency between clients, and the sync of position updates. Basically, the positions were always synced, but due to ping the position on clientside for other players/blocks will be different, potentially causing a magical block displacement.

How I've attempted to fix is just to let the transform parent do the work, and only update the position from direct network updates if it has no transform parent, and therefore no other way to move besides collisions.

**Comment by scryptonite** [comment]
@Salads your changes look like they are working 👍

The block synchronization might need a little more work long term because I observed the blocks on newly joined clients to replay their entire life when a user joins the room, but otherwise everything looks very good 😄

**Comment by Salads** [comment]
I figured out a way to fix it after some tinkering with RPCs, but the stream is live right now so I'll have to wait haha

**Comment by Salads** [comment]
Ok so just for completeness I'm going to go over the concepts being used here.

There's basically two main ways of sending data over the network. 

1. `OnPhotonSerializeView` updates at a constant rate (10/s by default, changeable with `PhotonNetwork.sendRate` and `PhotonNetwork.sendRateOnSerialize`) and whatever class implements it must be added to the observable components section of the PhotonView. Good for things that change allot, like position, rotation, and health.
2. `RPC` are functions that can be called remotely on any client. They don't update constantly, only when specifically called via `PhotonView.RPC` Good for things like picking up a block or sending a chat message. They are automatically added to PhotonServerSettings, but not automatically deleted. If one desires, you can go to the PhotonServerSettings file in the Unity Editor and click "Clear RPCs" and then "Refresh RPCs" to get a fresh list with no "extra" RPC entries. 

There are some other callbacks that get called when certain things happen, like `OnPhotonPlayerConnected(PhotonPlayer newPlayer)` which we can use to sync the joining player. 

The Master Client is the "host" of the server/room. `PhotonNetwork.IsMasterClient` will determine whether `stream.IsWriting == true`, or in other words whether the object is sending the updates or receiving them in  `OnPhotonSerializeView`. 
If the Master Client leaves, all scene instantiated objects will transfer to the new Master Client, and that new Master Client will now be the one sending the updates.

In this fork, I've synced the minigameBlocks mainly by using 'OnPhotonSerializeView' to update position and rotation, and `OnPhotonPlayerConnected(PhotonPlayer newPlayer)` to know when a new player connects and make the master client send an RPC to the new player with updated position/parent ID.

I remove the PhotonTransformView, because it's just a helper class that applies a Lerp to the transform automatically. It does this with `OnPhotonSerializeView`, hidden away from the user. It was bad for parenting because it is always on, and it directly edits the world coordinates making transforms buggy when trying to edit local transforms.

Testing shows that it works normally, however after _two_ master client changes, the next person to join will not see the block in the correct position. (it will be under the platform) still trying to figure out why.

**Comment by TalimaVale** [comment]
Awesome! Just synced up, and will test on stream tonight.

**Pull request closed without merging**
